fix [refractionPOINT/tracking#3025] Fix Docker image build + push workflow (#160)
* fix [refractionPOINT/tracking#3025] Fix Docker image build + push
workflow.

* fix [refractionPOINT/tracking#3025] Fix broken dockerfile.

* chore: [refractionPOINT/tracking#3025] Add TODO comment for future
improvement.

* chore: [refractionPOINT/tracking#3025] Use standard Docker image and
install various test dependencies into it.

This way we can auto retry on failure to try to auto mitigate for flaky
tests / race conditions in integration tests.

* chore: [refractionPOINT/tracking#3025] Add some docs on how to use
Docker image.

* chore: [refractionPOINT/tracking#3025] Update changelog.

* chore: [refractionPOINT/tracking#3025] Also run sdist sanity checks on
CI.

* feat: [refractionPOINT/tracking#3025] Update release workflow to also
version Docker image.

* chore: [refractionPOINT/tracking#3025] Bump version.

* chore: [refractionPOINT/tracking#3025] Update changelog.

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -1,16 +1,70 @@
 steps:
-- name: 'gcr.io/${PROJECT_ID}/pytest_3'
-  args: [ '-v', 'tests', '--oid', '${_OID}', '--key', '${_KEY}' ]
-- name: 'gcr.io/cloud-builders/docker'
+- id: "Run Unit Tests"
+  name: "python:3.11-slim"
+  entrypoint: "bash"
+  args:
+    - "-c"
+    - |
+      pip install --upgrade pip
+      pip install -r requirements.txt
+      pip install -r requirements-tests.txt
+
+      pytest -s -v --durations=10 --reruns 3 --reruns-delay 5 tests/unit/
+
+- id: "Run Integration Tests"
+  name: "python:3.11-slim"
+  entrypoint: "bash"
+  args:
+    - "-c"
+    - |
+      pip install --upgrade pip
+      pip install -r requirements.txt
+      pip install -r requirements-tests.txt
+
+      # We use rerun since tests are flaky
+      pytest -s -v --durations=10 --reruns 3 --reruns-delay 10 tests/integration/ --oid=${_OID} --key=${_KEY}
+
+- id: "Get Version"
+  name: "python:3.11-slim"
+  entrypoint: "bash"
+  args:
+    - "-c"
+    - |
+      _VERSION=$(python setup.py --version 2> /dev/null)
+      [ -n "$$_VERSION" ] || { echo "ERROR: _VERSION is empty or not set"; exit 1; };
+      echo $$_VERSION > version.txt
+      echo "Using Docker tag version: $$_VERSION"
+
+- id: "Login to DockerHub"
+  name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   args: ['-c', 'docker login --username=$$USERNAME --password=$$PASSWORD']
   secretEnv: ['USERNAME', 'PASSWORD']
-- name: 'gcr.io/cloud-builders/docker'
+
+- id: "Build Docker Image"
+  name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
-  args: ['-c', 'docker build -f ./Dockerfile -t refractionpoint/limacharlie:latest .']
-- name: 'gcr.io/cloud-builders/docker'
+  args:
+    - "-c"
+    - |
+      _VERSION=$(cat version.txt)
+      [ -n "$$_VERSION" ] || { echo "ERROR: _VERSION is empty or not set"; exit 1; };
+      docker build -f ./Dockerfile \
+        -t refractionpoint/limacharlie:latest \
+        -t refractionpoint/limacharlie:$$_VERSION \
+        .
+
+- id: "Push Image to Docker Hub"
+  name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
-  args: ['-c', 'docker push refractionpoint/limacharlie:latest']
+  args:
+    - "-c"
+    - |
+      _VERSION=$(cat version.txt)
+      [ -n "$$_VERSION" ] || { echo "ERROR: _VERSION is empty or not set"; exit 1; };
+      docker push refractionpoint/limacharlie:latest
+      docker push refractionpoint/limacharlie:$$_VERSION || true
+
 availableSecrets:
   secretManager:
   - versionName: projects/${PROJECT_ID}/secrets/DOCKERHUB/versions/latest
